site_name: Stargazer1011
site_url: https://stargazer1011.github.io/
site_description: moog moog moog moog moog
site_author: Stargazer 

theme:
  name: material
  palette:
    scheme: moog
  icon:
    repo: fontawesome/brands/github
  logo: img/moog.jpeg
  favicon: img/moog.jpeg
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - 'Build Log':
    - 'Build log test':
        - 'Build log #1': 'build_log_1.md'
  - 'Misc':
    - 'MarathonTraining Schedule': 'zero_to_marathon_training.md'

#steps to push code to github from vscode

#git add .
#git status (optional)
#git commit -m 'add commit message here'
#git push origin main