site_name: Stargazer1011
site_url: https://stargazer1011.github.io/
theme:
  name: material
  palette:
    scheme: moog
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - 'Build Log':
    - 'Build log #1': 'build_log_1.md'